db:
  username: ${username.value:postgres}
  password: postgres
  driver: PostgresDriver
  url: Postgres:5432
  host: localhost, 127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring.profiles.active: qa

logging:
  level:
    root: info
    com.greem4.spring.database.pool: info
    org.springframework.jdbc.core: trace
  file:
    name: loggingFile.log
    path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: 75b78df4cd814813ad38b9fd359cf446
            client-secret: 761f701688d04b01b8b35adc5b4939bd
            redirect-uri: http://localhost:8080/login/oauth2/code/yandex
            authorization-grant-type: authorization_code
            client-name: Yandex
            provider: yandex
            scope:
              - "login:email"
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id
  messages:
    basename: messages


springdoc:
    swagger-ui:
      oauth:
        client-id: 75b78df4cd814813ad38b9fd359cf446
        client-secret: 761f701688d04b01b8b35adc5b4939bd
